---
title: "Analysebok for Norsk Gynekologisk Endoskopiregister"
author: "Are Edvardsen mfl"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Beskrivelse av hva vi gjør fra rådata til ferdige resultater...

## Pasientkarakteristika
### Tabell med BMI, fødsler, svangerskap og operasjonstid

## Komplikasjoner
Figurer og tabeller relatert til registrerte komplikasjoner

### Tabell med fordeling (%) av laparoskopiske postoperative komplikasjoner
Tallene hentes fra Oppfølgingsskjema og filtreres på _OpType = 1_
(laparoskopiske inngrep/hendelse). Det første
som registreres er om det finnes komplikasjoner (_ComplExist_) og hvis så er tilfelle registreres det i fem ulike komplikasjonskategorier:

- Reoperasjon
- Infeksjon
- Blødning
- Organskade/defekt utstyr

Hver av disse har flere underkategorier. Hierarkiet blir da slik:

_OpType_ -> _ComplExist_ -> kategori -> underkategori

Ved en komplikasjon er det på samme person mulig å
velge flere kategorier og underkategorier. Det er også mulig å velge kategori
uten å spesifisere underkatergori. Til sammen gir dette litt begrenset mulighet
for å kontrollregne på antall...

I skjema registreres alt i avkryssingsbokser. Hver variable tar da verdiene
0, 1 eller NULL/NA der 1 er kryss og 0 ikke kryss. Det er antatt at NULL/NA
er standard verdi som fylles ut for alle forløp og denne verdien representerer
tilfelle der kategorien i nivået over har verdien 0 eller NULL/NA.

Det er per mars 2016 ingen sjekk på om forløpene som brukes faktisk er
ferdigstilte...
